# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 501)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(280, 160, 51, 20))
        self.label.setObjectName("label")
        self.txt_username = QtWidgets.QLineEdit(parent=Form)
        self.txt_username.setGeometry(QtCore.QRect(320, 160, 113, 20))
        self.txt_username.setObjectName("txt_username")
        self.txt_pwd = QtWidgets.QLineEdit(parent=Form)
        self.txt_pwd.setGeometry(QtCore.QRect(320, 200, 113, 20))
        self.txt_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_pwd.setObjectName("txt_pwd")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(280, 200, 51, 20))
        self.label_2.setObjectName("label_2")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(270, 310, 75, 24))
        self.btn_login.setObjectName("btn_login")
        self.btn_reset = QtWidgets.QPushButton(parent=Form)
        self.btn_reset.setGeometry(QtCore.QRect(380, 310, 75, 24))
        self.btn_reset.setObjectName("btn_reset")
        self.radio_admin = QtWidgets.QRadioButton(parent=Form)
        self.radio_admin.setGeometry(QtCore.QRect(330, 260, 95, 20))
        self.radio_admin.setObjectName("radio_admin")
        self.radio_user = QtWidgets.QRadioButton(parent=Form)
        self.radio_user.setGeometry(QtCore.QRect(410, 260, 95, 20))
        self.radio_user.setChecked(True)
        self.radio_user.setObjectName("radio_user")
        self.check_pwd = QtWidgets.QCheckBox(parent=Form)
        self.check_pwd.setGeometry(QtCore.QRect(230, 260, 79, 20))
        self.check_pwd.setObjectName("check_pwd")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "25软件5班"))
        self.label.setText(_translate("Form", "账号："))
        self.txt_username.setText(_translate("Form", "admin"))
        self.txt_pwd.setText(_translate("Form", "123"))
        self.label_2.setText(_translate("Form", "密码："))
        self.btn_login.setText(_translate("Form", "登录"))
        self.btn_reset.setText(_translate("Form", "重置"))
        self.radio_admin.setText(_translate("Form", "管理员"))
        self.radio_user.setText(_translate("Form", "普通用户"))
        self.check_pwd.setText(_translate("Form", "记住密码"))
